services:
  server:
    build: .
    container_name: node-jest
    env_file:
      - ./app/.env
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped