name: Node.js CI

on:
  push:
    branches: ["main"]
    paths:
      - "node-cicd/app/**" 
  pull_request:
    branches: ["main"]
    paths:
      - "node-cicd/app/**"

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] 

    defaults:
      run:
        working-directory: ./node-cicd/app 

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "node-cicd/app/pnpm-lock.yaml"

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Run build (if present)
        run: pnpm run build --if-present

      - name: Run tests
        run: pnpm test
        env:
          CI: true

      - name: Check types
        run: pnpm run type-check

      - name: Run linter
        run: pnpm run lint
