name: Node.js CI

on:
  push:
    branches: ["main"]
    path:
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [node-cicd]
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm" # Cambiado a pnpm
          cache-dependency-path: ${{ matrix.project }}/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run build (if present)
        run: pnpm run build --if-present

      - name: Run tests
        run: pnpm test
        env:
          CI: true # Importante para Jest en entornos CI
      - name: Check types
        run: pnpm run type-check
      - name: Run linter
        run: pnpm run lint
